require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

abstract_target 'environment_multi' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-config', :path => '../node_modules/react-native-config'

  target 'deekay_environment_multi_staysure' do
    
  end

  target 'deekay_environment_multi_avanti' do
    
  end

  target 'deekay_environment_multiTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'deekay_environment_multi-tvOS' do
  # Pods for deekay_environment_multi-tvOS

  target 'deekay_environment_multi-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
